import os
import re
import textwrap
from PIL import Image, ImageOps

# ==========================================
# SETTINGS
# ==========================================
IN_DIR = 'c/pic/digits-profile'  
OUT_FILE = 'c/lib/Fonts/font9_segoe.c'  # <-- Filename updated
FONT_NAME = 'Font9_Segoe'               # <-- Variable Name updated

def process_glyph(path):
    # 1. Load Image
    img = Image.open(path).convert("L")
    
    # 2. Invert (Black text -> White text for Alpha)
    img = ImageOps.invert(img)
    
    # 3. Clean absolute black noise (Optional)
    img = img.point(lambda p: p if p > 10 else 0)
    
    w, h = img.size
    return list(img.getdata()), w, h

def main():
    if not os.path.exists(IN_DIR):
        print(f"Error: Folder {IN_DIR} not found.")
        return

    mapping = {}
    files = sorted([f for f in os.listdir(IN_DIR) if f.endswith('.bmp')])
    
    detected_w = 0
    detected_h = 0
    
    # Scan files
    for f in files:
        fn = f.lower()
        path = os.path.join(IN_DIR, f)
        idx = -1
        
        # Detect Numbers 0-9
        m = re.search(r"^(\d)\.bmp", fn)
        if m: 
            idx = ord(m.group(1))
            
        if idx != -1:
            data, w, h = process_glyph(path)
            
            # Set global size based on the first image found
            if detected_w == 0:
                detected_w, detected_h = w, h
                print(f"Detected Font Size: {detected_w}x{detected_h}")
            
            if w != detected_w or h != detected_h:
                print(f"WARNING: Size mismatch in {f} ({w}x{h}). Expected {detected_w}x{detected_h}")

            mapping[idx] = data
            print(f"Processed: {f} -> ASCII {idx}")

    if detected_w == 0:
        print("No valid images found!")
        return

    # Generate Arrays (ASCII 32-126)
    start, count = 32, 95
    table_data = []
    width_data = []

    for i in range(start, start + count):
        if i in mapping:
            table_data.extend(mapping[i])
            width_data.append(detected_w) 
        else:
            table_data.extend([0] * (detected_w * detected_h))
            width_data.append(detected_w // 2)

    # Convert to Hex
    hex_rows = [", ".join([f"0x{b:02X}" for b in table_data[j:j+12]]) for j in range(0, len(table_data), 12)]
    
    # Write C File
    with open(OUT_FILE, 'w') as f:
        f.write(textwrap.dedent(f"""
            #include "fonts.h"
            #include <stdint.h>

            // Font generated by scripts/generate_font9_segoe.py
            // Source: {IN_DIR}
            // Detected Size: {detected_w}x{detected_h}

            const uint8_t {FONT_NAME}_Table[] = {{
                {",\n\t".join(hex_rows)}
            }};

            const uint8_t {FONT_NAME}_Widths[] = {{ {", ".join(map(str, width_data))} }};

            sFONT {FONT_NAME} = {{ {FONT_NAME}_Table, {detected_w}, {detected_h} }};
        """))
        
    print(f"\nSuccess! Generated {OUT_FILE}")
    print(f"Final Font Struct: {FONT_NAME} ({detected_w}x{detected_h})")

if __name__ == '__main__':
    main()